# Generated by Django 2.1.5 on 2019-09-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydb',
            name='contents',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='mydb',
            name='writer',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
