# Generated by Django 2.1.5 on 2019-09-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190902_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('tag', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='boardConf',
        ),
    ]
