# Generated by Django 2.1.5 on 2019-09-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mydb_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydb',
            name='pwd',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
