# Generated by Django 2.1.5 on 2019-09-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190902_1951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myapp',
            new_name='myDB',
        ),
    ]
