# Generated by Django 2.1.5 on 2019-09-07 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_mydb_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_contents', models.CharField(max_length=100)),
                ('c_date', models.DateTimeField(auto_now_add=True)),
                ('c_like', models.IntegerField(default=0)),
                ('c_dislike', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='myDB',
            new_name='Board_DB',
        ),
        migrations.AddField(
            model_name='comment_db',
            name='c_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.Board_DB'),
        ),
        migrations.AddField(
            model_name='comment_db',
            name='c_writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
