# Generated by Django 2.1.5 on 2019-09-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190907_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_db',
            name='c_contents',
            field=models.TextField(default=''),
        ),
    ]
