# Generated by Django 2.1.5 on 2019-09-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190908_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_db',
            name='c_writer',
            field=models.CharField(default='익명의 동글', max_length=10),
        ),
    ]
